[build]
  publish = "."

[[headers]]
  for = "/*"
  [headers.values]
    X-Frame-Options = "ALLOWALL"
    Content-Security-Policy = "frame-ancestors *"
    X-Content-Type-Options = "nosniff"
    Referrer-Policy = "strict-origin-when-cross-origin"

# Optimisations de performance
[[headers]]
  for = "*.html"
  [headers.values]
    Cache-Control = "public, max-age=300"

[[headers]]
  for = "*.css"
  [headers.values]
    Cache-Control = "public, max-age=31536000"

[[headers]]
  for = "*.js"
  [headers.values]
    Cache-Control = "public, max-age=31536000"

# Configuration spécifique pour les pages de séquences
[[headers]]
  for = "/pages/*"
  [headers.values]
    X-Frame-Options = "ALLOWALL"
    Content-Security-Policy = "frame-ancestors *"

[[redirects]]
  from = "/api/*"
  to = "/.netlify/functions/:splat"
  status = 200

# Redirections si nécessaire
[[redirects]]
  from = "/old-page"
  to = "/index.html"
  status = 301

# Redirections si nécessaire
[[redirects]]
  from = "/old-page"
  to = "/index.html"
  status = 301

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

[functions]

  [functions.GITHUB_TOKEN]
  external_node_modules = [
    "module-one",
    "module-two"
  ]
